package com.nco.enums;

public enum Skills {
    A_V_TECH(1),
    ACCOUNTING(1),
    ACTING(1),
    ANIMAL_HANDLING(1),
    ARCHERY(1),
    ATHLETICS(1),
    AUTOFIRE(2),
    BASIC_TECH(1),
    BRAWLING(1),
    BRIBERY(1),
    BUREAUCRACY(1),
    BUSINESS(1),
    COMPOSITION(1),
    CONCEAL_REVEAL(1),
    CONCENTRATION(1),
    CONTORTIONIST(1),
    CONVERSATION(1),
    CRIMINOLOGY(1),
    CRYPTOGRAPHY(1),
    CYBERTECH(1),
    DANCE(1),
    DEDUCTION(1),
    DEMOLITIONS(2),
    DRIVE_LAND(1),
    EDUCATION(1),
    ELECTRONICS_SECURITY(2),
    ENDURANCE(1),
    EVASION(1),
    FIRST_AID(1),
    FORGERY(1),
    GAMBLE(1),
    HANDGUN(1),
    HEAVY_ARMS(2),
    HUMAN_PERCEPTION(1),
    INSTRUMENT_A(1),
    INSTRUMENT_B(1),
    INTERROGATION(1),
    L_V_TECH(1),
    LANGUAGE_A(1),
    LANGUAGE_B(1),
    LIBRARY_SEARCH(1),
    LIP_READING(1),
    LOCAL_EXPERT_A(1),
    LOCAL_EXPERT_B(1),
    MARTIAL(2),
    MELEE(1),
    PAINT_DRAW_SCULPT(1),
    PARAMEDIC(2),
    PERCEPTION(1),
    PERSONAL_GROOMING(1),
    PERSUASION(1),
    PHOTOGRAPHY_FILM(1),
    PICK_LOCK(1),
    PICK_POCKET(1),
    PILOT_AIR(2),
    PILOT_SEA(1),
    RIDING(1),
    S_V_TECH(1),
    SCIENCE_A(1),
    SCIENCE_B(1),
    SHOULDER_ARMS(1),
    STEALTH(1),
    STREETSLANG(1),
    STREETWISE(1),
    TACTICS(1),
    TORTURE_DRUGS(1),
    TRACKING(1),
    TRADING(1),
    WARDROBE(1),
    WEAPONSTECH(1),
    WILDERNESS(1),
    YOUR_HOME(1);

    public final int difficulty;

    Skills(int difficulty) {
        this.difficulty = difficulty;
    }

    @Override
    public String toString() {
        return name().toLowerCase();
    }
}
